language: node_js
node_js:
- '6'
script: npm run dist
deploy:
  provider: npm
  email: dev@nhz.io
  skip_cleanup: true
  api_key:
    secure: BtnasFBxWrk8roxuHLOQJBzHOMhz031Mh9ZbZePx3scckNhHSc0AC/rQ+2A3UskjvhRhLtGya/MLTmRKE4Qqg57MCSsw2TQhDBrI7vcgxe3fE67IRv+E6bY3DBu5WZyYL+klKynXDJ/J3SNIaLTsKqr4qW35uGgQzJNI4okrsbgtG62w0VsV0uT9EH2nYrEMT5+qAeEOdQuAhwQQUP2nYYsh4yH48UvLJbmMAPRZky9TPDq4ZZrJimxrAfoxvYtpFPEe5TKP7IpaqGvLuYrhGFX3rbgw88G3gTuTdcAIrQZ/yN8T5cn/JoTRFI8h5uDUF2X+jaEFvs4MF3YOFden2kTxUJNU71axJo45RTOFzDPrkyf1iTZ08PnGfur1Ji9Un8UfkfdZT34KvTsSB/B7ysa0xA26mVP6dBMLlwhdUxxX5srxbWf0eJuft+XuAf03C8U6X8HsHrWmBTHyKTPPO2LgepO2105ZMNLuX+NGBBAP4xb73vXTCv7yJtWJUJwUglFTx/jLWuNFtaF6LN89puXjvd8qD9ywUkAJMKwmWsilvcALJZiqQMloGFfST9HUrWHsQWd68t19hINA4e3x6SqmN204Z8PyS9UZQvG/iLE05pBBNf4K4YJ/QMVKW7q0XWliVD0MqUEX/eh3QWlAHRcTbkanoMrW2Ols4hanDKo=
  on:
    tags: true
    branch: master
    repo: nhz-io/inferno-canvas-component
